//! Compiles the application icon into the executable, so Explorer and a pinned taskbar shortcut
//! show it. The running window sets its own icon separately, from `assets/window-icon.rgba`.
//!
//! Both files are generated by `scripts/make-icon.ps1` and committed; this only embeds them.
fn main() {
    let assets = std::path::Path::new("../../assets");
    println!("cargo:rerun-if-changed=build.rs");
    println!(
        "cargo:rerun-if-changed={}",
        assets.join("duckie.ico").display()
    );
    if !cfg!(target_os = "windows") {
        return;
    }
    let icon = assets.join("duckie.ico");
    if !icon.exists() {
        // A missing icon must not stop a build; the app simply falls back to the default one.
        println!(
            "cargo:warning={} is missing; run scripts/make-icon.ps1",
            icon.display()
        );
        return;
    }
    let mut resource = winresource::WindowsResource::new();
    resource.set_icon(&icon.to_string_lossy());
    resource.set("FileDescription", "Duckie");
    resource.set("ProductName", "Duckie");
    resource.set(
        "LegalCopyright",
        "Copyright (c) 2026 Jes Bak Hansen. MIT licensed.",
    );
    if let Err(e) = resource.compile() {
        println!("cargo:warning=Could not embed the application icon: {e}");
    }
}
